### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BootzenKatzen** [Tavnos/Towers-of-Atlantis#1]
It looks like you put a lot of work into this... but I can't seem to get it to run...  I'm going to poke at it a bit myself, to see if I can resolve anything, but I figured I'd send along my error message so you could look into it as well.

[error.txt](https://github.com/Tavnos/Towers-of-Atlantis/files/3561250/error.txt)

**Comment by BootzenKatzen** [comment]
I'm wondering if it's because I'm on a Windows computer, and it seems that  you've used a Mac... though I thought Python was supposed to be readable on any system.

**Comment by Tavnos** [comment]
Will look into it

**Comment by Tavnos** [comment]
The issue should have been solved by now, I hope it will work on your end, and by all means, feel free to open another issue if you run into an error again. Thanks for helping!
